export enum CommonCode {
	VALIDATION_ERROR = 'VALIDATION_ERROR',
	UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
	INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
	BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
	NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
	CONFLICT_ERROR = 'CONFLICT_ERROR',
}
